apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sagaz

commonLabels:
  app.kubernetes.io/name: sagaz
  app.kubernetes.io/part-of: sagaz-platform

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - outbox-worker.yaml
