apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - monitoring-stack.yaml
  - prometheus-alerts.yaml

configMapGenerator:
  - name: sagaz-grafana-dashboards
    files:
      - grafana-dashboard-main.json
      - grafana-dashboard-outbox.json
    options:
      labels:
        grafana_dashboard: "1"

labels:
  - pairs:
      app.kubernetes.io/part-of: sagaz
      app.kubernetes.io/managed-by: kustomize
